metadata:
  occurrences:
    units: /min
    precision: 2
triggers:
  - type: trend
    dname: occurrences
    direction: UP
    percentage_change: 300
    duration: 60
    window_reference: LAST_WEEK